steps:
  - name: 'gcr.io/cloud-builders/git'
    args: [
          'checkout origin/dev'
      ]

  - name: 'gcr.io/$PROJECT_ID/terraform'
    args: [
        'init'
    ]
  - name: 'gcr.io/$PROJECT_ID/terraform'
    entrypoint: 'bash'
    args: [
        '-c',
        'terraform plan -no-color > plan.txt'
    ]

