steps:

- id: "tf init"
  name: "hashicorp/terraform:1.0.0"
  entrypoint: "sh"
  args:
  - "-c"
  - |
      echo "***********************"
      echo "$BRANCH_NAME"
      echo "***********************"
      terraform init

- id: "tf plan"
  name: "hashicorp/terraform:1.0.0"
  entrypoint: "sh"
  args:
  - "-c"
  - |
      echo "***********************"
      echo "PLANNING"
      echo "***********************"
      terraform plan -out=test.tfplan

  # name: gcr.io/config-validator/terraform-validator
  # entrypoint: terraform
  # args:
  # - plan
  # - -out=terraform.plan

- id: "convert output to json"
  # name: gcr.io/config-validator/terraform-validator
  # entrypoint: "/bin/bash"
  # args: ["-c", "terraform show -json terraform.plan > terraform.json"]
  name: "hashicorp/terraform:1.0.0"
  entrypoint: "sh"
  args:
  - "-c"
  - |
      echo "***********************"
      echo "CONVERTING"
      echo "***********************"
      terraform show -json ./test.tfplan > ./tfplan.json

- id: "validate policies"
  name: gcr.io/config-validator/terraform-validator
  args:
  - validate
  - terraform.json
  - --policy-path=./policy-folder

- id: "tf apply"
  name: "hashicorp/terraform:1.0.0"
  entrypoint: "sh"
  args:
  - "-c"
  - |
      echo "***********************"
      echo "$BRANCH_NAME"
      echo "***********************"
      terraform init
