steps:

- id: 'branch name'
  name: 'alpine'
  entrypoint: 'sh'
  args:
  - '-c'
  - |
      echo "***********************"
      echo "$BRANCH_NAME"
      echo "***********************"

- id: 'tf init'
  name: 'hashicorp/terraform:1.0.0'
  entrypoint: 'sh'
  args: ["terraform init"]


# - name: gcr.io/config-validator/terraform-validator
#   entrypoint: terraform
#   args:
#   - init

# - name: gcr.io/config-validator/terraform-validator
#   entrypoint: terraform
#   args:
#   - plan
#   - -out=terraform.plan

# - name: gcr.io/config-validator/terraform-validator
#   entrypoint: "/bin/bash"
#   args: ["-c", "terraform show -json terraform.plan > terraform.json"]


# - name: gcr.io/config-validator/terraform-validator
#   args:
#   - validate
#   - terraform.json
#   - --policy-path=./policy-folder

# # - name: "gcr.io/${PROJECT_ID}/terraform"
# #   args: ["apply", "-auto-approve"]
# #   env:
# #     - "TF_VAR_project-name=${PROJECT_ID}"

# - id: "tf apply"
#   name: "hashicorp/terraform:1.0.0"
#   entrypoint: "sh"
#   args: ["apply", "auto-approve"]
