availableSecrets:
  secretManager:
  - versionName: projects/w-appdev-0805/secrets/secret-name/versions/latest
    env: 'SSH_KEY'

steps:
- name: 'gcr.io/cloud-builders/git'
  secretEnv: ['SSH_KEY']
  entrypoint: 'bash'
  args:
  - -c
  - |
    echo "$$SSH_KEY" >> /root/.ssh/id_rsa
    chmod 400 /root/.ssh/id_rsa
    cp known_hosts.github /root/.ssh/known_hosts
  volumes:
  - name: 'ssh'
    path: /root/.ssh

# Clone the repository
- name: 'gcr.io/cloud-builders/git'
  args:
  - clone
  - git@github.com:lykaasegura/w-secteam-repo.git
  volumes:
  - name: 'ssh'
    path: /root/.ssh/

- id: "tf init"
  name: gcr.io/config-validator/terraform-validator
  entrypoint: terraform
  args:
  - init

- id: "tf plan"
  name: gcr.io/config-validator/terraform-validator
  entrypoint: terraform
  args:
  - plan
  - -out=terraform.plan

- id: "convert output to json"
  name: gcr.io/config-validator/terraform-validator
  entrypoint: "/bin/bash"
  args: ["-c", "terraform show -json terraform.plan > terraform.json"]

- id: "validate policies"
  name: gcr.io/config-validator/terraform-validator
  args:
  - validate
  - terraform.json
  - --policy-path=./w-secteam-repo/policy-folder

# - id: "tf apply"
#   name: gcr.io/config-validator/terraform-validator
#   entrypoint: terraform
#   args:
#   - apply
#   - -auto-approve


