steps:

- id: "tf init"
  name: gcr.io/config-validator/terraform-validator
  entrypoint: "/bin/bash"
  args:
  - init

- id: "tf plan"
  name: gcr.io/config-validator/terraform-validator
  entrypoint: terraform
  args:
  - plan
  - -out=terraform.plan

- id: "convert output to json"
  name: gcr.io/config-validator/terraform-validator
  entrypoint: "/bin/bash"
  args: ["-c", "terraform show -json terraform.plan > terraform.json"]

- id: "validate policies"
  name: gcr.io/config-validator/terraform-validator
  args:
  - validate
  - terraform.json
  - --policy-path=./policy-folder

- id: "tf apply"
  # name: "hashicorp/terraform:1.0.0"
  # entrypoint: "sh"
  # args:
  # - "-c"
  # - |
  #     echo "***********************"
  #     echo "$BRANCH_NAME"
  #     echo "***********************"
  #     terraform apply -auto-approve
  name: gcr.io/config-validator/terraform-validator
  entrypoint: "/bin/bash"
  args:
  - apply
  - -auto-approve
