# steps:
# - name: 'gcr.io/cloud-builders/git'
#   args:
#   - clone
#   - https://github.com/lykaasegura/w-secteam-repo.git
substitutions:
  _TERRAFORM_VERSION: 1.0.9
  _TERRAFORM_VERSION_SHA256SUM: f06ac64c6a14ed6a923d255788e4a5daefa2b50e35f32d7a3b5a2f9a5a91e255
  _BUCKET: "w-appdev-0805-tfstate"

images:
  - 'gcr.io/${PROJECT_ID}/terraform:${_TERRAFORM_VERSION}'
  - 'gcr.io/${PROJECT_ID}/terraform:latest'

steps:

- name: 'gcr.io/cloud-builders/wget'
  args: ["https://releases.hashicorp.com/terraform/${_TERRAFORM_VERSION}/terraform_${_TERRAFORM_VERSION}_linux_amd64.zip"]
- name: 'gcr.io/cloud-builders/docker'
  env:
  - 'TERRAFORM_VERSION=${_TERRAFORM_VERSION}'
  - 'TERRAFORM_VERSION_SHA256SUM=${_TERRAFORM_VERSION_SHA256SUM}'
  args:
  - build
  - --build-arg
  - TERRAFORM_VERSION=${_TERRAFORM_VERSION}
  - --build-arg
  - TERRAFORM_VERSION_SHA256SUM=${_TERRAFORM_VERSION_SHA256SUM}
  - --tag
  - gcr.io/${PROJECT_ID}/terraform:${_TERRAFORM_VERSION}
  - --tag
  - gcr.io/${PROJECT_ID}/terraform:latest
  - .
- name: 'gcr.io/${PROJECT_ID}/terraform:${_TERRAFORM_VERSION}'
  args: ['version']

- name: 'gcr.io/${PROJECT_ID}/terraform'
  args: ['init',
    '-backend-config=bucket=${_BUCKET}', '-reconfigure']
  env:
    - "TF_VAR_project=${PROJECT_ID}"
    - "TF_VAR_region=${_REGION}"
    - "TF_VAR_zone=${_ZONE}"
- name: 'gcr.io/${PROJECT_ID}/terraform'
  args: ['plan']
  env:
    - "TF_VAR_project=${PROJECT_ID}"
    - "TF_VAR_region=${_REGION}"
    - "TF_VAR_zone=${_ZONE}"

tags: ['cloud-builders-community']

# - id: "tf init"
#   name: gcr.io/config-validator/terraform-validator
#   entrypoint: terraform
#   args:
#   - init

# - id: "tf plan"
#   name: gcr.io/config-validator/terraform-validator
#   entrypoint: terraform
#   args:
#   - plan
#   - -out=terraform.plan

# - id: "convert output to json"
#   name: gcr.io/config-validator/terraform-validator
#   entrypoint: "/bin/bash"
#   args: ["-c", "terraform show -json terraform.plan > terraform.json"]

# - id: "validate policies"
  # name: gcr.io/config-validator/terraform-validator
  # args:
  # - validate
  # - terraform.json
  # - --policy-path=./w-secteam-repo

  # name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
  # entrypoint: bash
  # args:
  #     - "beta"
  #     - "run"

# - id: "tf apply"
#   name: gcr.io/config-validator/terraform-validator
#   entrypoint: terraform
#   args:
#   - apply
#   - -auto-approve


